CREATE TABLE CONSULTA_RISCO (
    USUARIO_ID NUMBER(10) NOT NULL,
    PROTOCOLO VARCHAR2(36) NOT NULL,
    REGIAO_MONITORADA_ID NUMBER(10) NOT NULL,
    PROMPT VARCHAR2(500) NOT NULL,
    LATITUDE NUMBER(9,6),
    LONGITUDE NUMBER(9,6),
    RUA_REGIAO VARCHAR2(120),
    NIVEL_RISCO VARCHAR2(20),
    RESPOSTA_IA VARCHAR2(500),
    CRIADO_EM TIMESTAMP,
    CONSTRAINT CONSULTA_RISCO_PK PRIMARY KEY (USUARIO_ID, PROTOCOLO),
    CONSTRAINT CONSULTA_RISCO_USUARIO_FK FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID),
    CONSTRAINT CONSULTA_RISCO_REGIAO_FK FOREIGN KEY (REGIAO_MONITORADA_ID) REFERENCES REGIAO_MONITORADA(ID)
);
